# Generated by Django 5.0.1 on 2024-02-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_matchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
