# Generated by Django 5.0.1 on 2024-02-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_matchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
