# Generated by Django 5.0.1 on 2024-02-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
